IF OBJECT_ID('pr_listarPropiedades') IS NOT NULL
	BEGIN 
		DROP PROC pr_listarPropiedades
	END
GO

CREATE PROC pr_listarPropiedades
AS
BEGIN

	PRINT '--------------------------------LISTA DE PROPIETARIOS------------------------------------------'
	
	DECLARE @DNI VARCHAR(100),@NOMBRE VARCHAR(100),@APELLIDO1 VARCHAR(100),@APELLIDO2 VARCHAR(100),@SEXO CHAR(1)
	
	DECLARE cur_Props CURSOR FOR
	SELECT DNI, NOMBRE , APELLIDO1, APELLIDO2, SEXO FROM PROPIETARIO
	
	OPEN cur_Props
	
		FETCH NEXT FROM cur_Props INTO @DNI,@NOMBRE,@APELLIDO1,@APELLIDO2,@SEXO
		
		WHILE @@FETCH_STATUS <> -1
		BEGIN 
			
			PRINT 'DNI PROPIETARIO: ' + @DNI + ' NOMBRE: ' + @NOMBRE + ' ' +ISNULL(@APELLIDO1,'') + ' ' + ISNULL(@APELLIDO2,' ') + ' SEXO: ' + @SEXO
			
				DECLARE cur_Pisos CURSOR FOR
				SELECT CALLE, NUMERO, PLANTA, PUERTA, NUMHABITACIONES, METROSUTILES, METROSCONSTRUIDOS 
				FROM PISO WHERE DNIPROPIETARIO = @DNI
				
				DECLARE @CALLE VARCHAR(100), @NUMERO INT, @PLANTA INT, @PUERTA CHAR(1), @NUMHABITACIONES INT, @METROSUTILES INT, @METROSCONSTRUIDOS INT
				
				OPEN cur_Pisos
				
				FETCH NEXT FROM cur_Pisos INTO @CALLE, @NUMERO, @PLANTA, @PUERTA, @NUMHABITACIONES, @METROSUTILES, @METROSCONSTRUIDOS
				
				PRINT '                                      PISOS'
				PRINT '------------------------------------------------------------------------------------------------'
				PRINT 'CALLE            NUMERO   PLANTA   PUERTA   NUMHABITACIONES   METROSUTILES   METROSCONSTRUIDOS'
				
				WHILE @@FETCH_STATUS <> -1 
				BEGIN
					PRINT @CALLE + '            ' + CAST(@NUMERO AS VARCHAR(100)) + '   '+ CAST(@PLANTA AS VARCHAR(100)) + '   '+ CAST(@PUERTA AS VARCHAR(100)) +'   ' + 
					CAST(@NUMHABITACIONES AS VARCHAR(100))+'   '+ CAST(@METROSUTILES AS VARCHAR(100)) +'   ' + CAST(@METROSCONSTRUIDOS AS VARCHAR(100)) 
					
					FETCH NEXT FROM cur_Pisos INTO @CALLE, @NUMERO, @PLANTA, @PUERTA, @NUMHABITACIONES, @METROSUTILES, @METROSCONSTRUIDOS
				END
					
				CLOSE cur_Pisos
				DEALLOCATE cur_Pisos
			
		
			FETCH NEXT FROM cur_Props INTO @DNI,@NOMBRE,@APELLIDO1,@APELLIDO2,@SEXO
		END
	
	CLOSE cur_Props
	DEALLOCATE cur_Props
	

END

EXEC pr_listarPropiedades