-- 1

ALTER TABLE PASTELERO
	ADD FECHABAJA DATE NULL

IF OBJECT_ID('prTraspaso') IS NOT NULL
BEGIN 
	DROP PROC prTraspaso
END

GO

CREATE PROC prTraspaso
@ALIASP1 VARCHAR(100),
@ALIASP2 VARCHAR(100),
@NRECETAS INT = 0 OUTPUT,
@NPASTELERIAS INT = 0 OUTPUT
AS 
BEGIN

	IF NOT EXISTS(SELECT 1 FROM PASTELERO WHERE ALIAS = @ALIASP1)
	BEGIN
		RETURN -1
	END
	
	IF NOT EXISTS(SELECT 1 FROM PASTELERO WHERE ALIAS = @ALIASP2)
	BEGIN
		RETURN -2
	END
	
	DECLARE @CODRECETA VARCHAR(100)
	
	DECLARE curRecetas CURSOR STATIC FOR
	SELECT CODIGO FROM RECETA WHERE CODPASTELERO = (SELECT CODIGO FROM PASTELERO WHERE ALIAS = @ALIASP1)
	
	OPEN curRecetas
		
		FETCH NEXT FROM curRecetas INTO @CODRECETA
		
		WHILE @@FETCH_STATUS <> -1
		BEGIN
		
			UPDATE RECETA
			SET CODPASTELERO = (SELECT CODIGO FROM PASTELERO WHERE ALIAS = @ALIASP2)
			WHERE CODPASTELERO = (SELECT CODIGO FROM PASTELERO WHERE ALIAS = @ALIASP1)
			
			SET @NRECETAS = @NRECETAS + 1
			
			FETCH NEXT FROM curRecetas INTO @CODRECETA
		END
		
	CLOSE curRecetas
	DEALLOCATE curRecetas
	
	DECLARE @CODPASTELERIA VARCHAR(100)
	DECLARE curPastelerias CURSOR FOR
	SELECT CODIGO FROM PASTELERIA WHERE CODPASTELERO = (SELECT CODIGO FROM PASTELERO WHERE ALIAS = @ALIASP1)
	
	OPEN curPastelerias
	
	FETCH NEXT FROM curPastelerias INTO @CODPASTELERIA
	
	WHILE @@FETCH_STATUS <> -1 
	BEGIN
		
		UPDATE PASTELERIA
		SET CODPASTELERO = (SELECT CODIGO FROM PASTELERO WHERE ALIAS = @ALIASP2)
		WHERE CODIGO = @CODPASTELERIA
		
		SET @NPASTELERIAS = @NPASTELERIAS + 1
		
		FETCH NEXT FROM curPastelerias INTO @CODPASTELERIA
	END 
	
	CLOSE curPastelerias
	DEALLOCATE curPastelerias
	
	
	UPDATE PASTELERO
	SET FECHABAJA = GETDATE()
	WHERE ALIAS = @ALIASP1
	
	RETURN 0
END

GO

IF OBJECT_ID('prMensajeTraspaso') IS NOT NULL
BEGIN 
	DROP PROC prMensajeTraspaso
END

GO

CREATE PROC prMensajeTraspaso
@ALIASP1 VARCHAR(100),
@ALIASP2 VARCHAR(100)
AS
BEGIN
	
	DECLARE @NRECETAS INT
	DECLARE @NPASTELERIAS INT
	DECLARE @RESULT INT
	
	EXEC @RESULT = prTraspaso 
	@ALIASP1 = @ALIASP1,
	@ALIASP2 = @ALIASP2,
	@NRECETAS = @NRECETAS OUTPUT,
	@NPASTELERIAS = @NPASTELERIAS OUTPUT
	
	IF @RESULT = -1
	BEGIN 
		PRINT 'NO EXISTE EL PRIMER PASTELERO'
	END
	
	IF @RESULT = -2
	BEGIN 
		PRINT 'NO EXISTE EL SEGUNDO PASTELERO'
	END
	
	IF @RESULT = 0
	BEGIN 
		PRINT 'SE HAN TRASPASADO ' + CAST(@NRECETAS AS VARCHAR(50)) + ' RECETAS Y ' + CAST(@NPASTELERIAS AS VARCHAR(50)) + ' PASTELERIAS DE  ' + @ALIASP1 + ' A ' + @ALIASP2
	END
	
	
END

GO

EXEC prMensajeTraspaso 'CARLIÑOS', 'ALBIÑA'

GO

IF OBJECT_ID('prIngredienteReceta') IS NOT NULL
BEGIN 
	DROP PROC prIngredienteReceta
END

GO

CREATE PROC prIngredienteReceta
@INGREDIENTE VARCHAR(100) = 'HUEVOS'
AS
BEGIN

	PRINT '--------------------------------LISTADO DE RECETAS QUE LLEVAN' + @INGREDIENTE + '--------------------------------'
	
	IF NOT EXISTS (SELECT 1 FROM INGREDIENTE WHERE NOME = @INGREDIENTE)
	BEGIN
		PRINT SPACE(15) + 'EL INGREDIENTE NO EXISTE EN LA BASE DE DATOS'
		RETURN
	END
	
	IF NOT EXISTS (SELECT COD_RECETA FROM RECETA_INGREDIENTE WHERE COD_INGREDIENTE = (SELECT CODIGO FROM INGREDIENTE WHERE INGREDIENTE.NOME = @INGREDIENTE))
	BEGIN 
		PRINT SPACE(15) + 'EL INGREDIENTE EXISTE PERO NO HAY NINGUNA RECETA QUE LO LLEVE'
		RETURN
	END
	
	DECLARE @NUMREC INT = 1
	
	DECLARE @NOMRECETA VARCHAR(100),@ALIAS VARCHAR(100),@DIFICULTAD VARCHAR(100), @TIEMPO FLOAT
	
	DECLARE curIngredientes CURSOR DYNAMIC FOR
	SELECT R.NOMBRE, P.ALIAS, R.DIFICULTAD, R.TIEMPO FROM INGREDIENTE I INNER JOIN RECETA_INGREDIENTE RI
	ON I.CODIGO = RI.COD_INGREDIENTE
	INNER JOIN RECETA R
	ON RI.COD_RECETA = R.CODIGO
	INNER JOIN PASTELERO P
	ON R.CODPASTELERO = P.CODIGO
	WHERE RI.COD_INGREDIENTE = (SELECT CODIGO FROM INGREDIENTE WHERE INGREDIENTE.NOME = @INGREDIENTE)
	
	OPEN curIngredientes
	
	FETCH NEXT FROM curIngredientes INTO @NOMRECETA, @ALIAS, @DIFICULTAD, @TIEMPO
	
	WHILE @@FETCH_STATUS <> -1
	BEGIN
		IF @@FETCH_STATUS = -2
		BEGIN 
			FETCH NEXT FROM curIngredientes INTO @NOMRECETA, @ALIAS, @DIFICULTAD, @TIEMPO
			CONTINUE
		END 
		
		PRINT 'RECETA ' + CAST(@NUMREC AS VARCHAR(15)) + '.......: ' + @NOMRECETA + ' PERTENECE A ' + @ALIAS
		PRINT SPACE(17) + 'DIFICULTADE: ' + @DIFICULTAD + ' TIEMPO: ' + CAST(@TIEMPO AS VARCHAR(15))
		PRINT ''
		
		SET @NUMREC = @NUMREC + 1
		FETCH NEXT FROM curIngredientes INTO @NOMRECETA, @ALIAS, @DIFICULTAD, @TIEMPO
	END
	
	CLOSE curIngredientes
	DEALLOCATE curIngredientes

END
GO

EXEC prIngredienteReceta 'LECHE'

GO